import Image from "next/image";

// Width variants generated by scripts/generate-image-variants.mjs.
// Every base .jpg in public/images has -768 and -1280 variants
// in jpg, webp, and avif.
const VARIANT_WIDTHS = [768, 1280];

// Intrinsic width of the full-size files, used as the largest
// srcset descriptor. Most photos are 1800px wide; exceptions below.
const DEFAULT_FULL_WIDTH = 1800;
const FULL_WIDTHS: Record<string, number> = {
  "/images/landing-bg": 2400,
  "/images/outdoor-dining": 1500,
};

function buildSrcSet(basePath: string, ext: "avif" | "webp"): string {
  const fullWidth = FULL_WIDTHS[basePath] ?? DEFAULT_FULL_WIDTH;
  return [
    ...VARIANT_WIDTHS.map((w) => `${basePath}-${w}.${ext} ${w}w`),
    `${basePath}.${ext} ${fullWidth}w`,
  ].join(", ");
}

interface OptimizedImageProps {
  src: string;
  alt: string;
  fill?: boolean;
  priority?: boolean;
  sizes?: string;
  className?: string;
  onLoad?: () => void;
}

export default function OptimizedImage({
  src,
  alt,
  fill,
  priority,
  sizes,
  className,
  onLoad,
}: OptimizedImageProps) {
  const basePath = src.replace(/\.jpg$/, "");
  const resolvedSizes = sizes ?? (fill ? "100vw" : undefined);

  return (
    <picture>
      <source
        srcSet={buildSrcSet(basePath, "avif")}
        sizes={resolvedSizes}
        type="image/avif"
      />
      <source
        srcSet={buildSrcSet(basePath, "webp")}
        sizes={resolvedSizes}
        type="image/webp"
      />
      <Image
        src={src}
        alt={alt}
        fill={fill}
        priority={priority}
        sizes={resolvedSizes}
        className={className}
        onLoad={onLoad}
      />
    </picture>
  );
}
