import type { GuideEntry } from "../types";

export const bars: GuideEntry[] = [
  {
    title: "Pukiki Tiki Bar",
    slug: "pukiki",
    tagline: "The largest rum selection on Madeira, in a bamboo room above the village.",
    location: "Estreito da Calheta",
    body: "\"Pukiki\" is what Hawaiians called the Madeirans who emigrated in 1878 to work the sugar plantations. The couple who run it have worked hard to bring their dream to life and you feel it the moment you walk in. Cocktails that are genuinely exceptional.",
    body2: "If you walk down, book a taxi back before 9pm; most drivers finish for the night.",
    practical: "Estreito da Calheta, 5 min from the house. Evening. Book a taxi back.",
    lastVerified: "2026-06-15",
    distanceKm: 3,
    travelMinutes: 5,
    contact: { instagram: "https://www.instagram.com/pukikitikibar/" },
    tags: ["cocktails", "rum", "evening"],
  },
  {
    title: "Poncha do Emanuel",
    slug: "poncha-do-emanuel",
    tagline: "The neighbourhood poncha spot.",
    location: "Arco da Calheta",
    body: "A few minutes by car from the house. The signature is poncha de alecrim, a rosemary infusion we have not found anywhere else. Plain room, locals at the bar, the right amount of late-afternoon weight.",
    body2: "Order one round to start; they will tell you which to have for the second.",
    practical: "Arco da Calheta, 3 min from the house. Afternoon and evening.",
    lastVerified: "2026-06-15",
    distanceKm: 1,
    travelMinutes: 3,
    tags: ["poncha", "local", "traditional"],
  },
  {
    title: "Poncha do Lombo do Doutor",
    slug: "poncha-lombo-do-doutor",
    location: "Near Arco da Calheta",
    body: "A short drive from the house, worth stopping on the way back from somewhere else rather than making a destination of it on its own. Adventurous flavour range: passion fruit, tangerine, eucalyptus, others depending on the season.",
    practical: "Near Arco da Calheta, 5 min from the house. Afternoon.",
    lastVerified: "2026-06-15",
    distanceKm: 3,
    travelMinutes: 5,
    tags: ["poncha", "local"],
  },
  {
    title: "Purple Fridays",
    slug: "purple-fridays",
    tagline: "Where the digital-nomad community gathers on Friday nights.",
    location: "Ponta do Sol",
    body: "Membership required, but if you are staying long enough that a few Fridays will pass, it pays for itself in introductions. The vibe sits somewhere between a private members' bar and a community gathering.",
    practical: "Ponta do Sol, 15 min from the house. Fridays only. Membership required.",
    lastVerified: "2026-06-15",
    distanceKm: 15,
    travelMinutes: 15,
    contact: { instagram: "https://www.instagram.com/thepurplefridays/" },
    tags: ["nomad", "community", "members"],
  },
  {
    title: "Doca do Cavacas",
    slug: "doca-do-cavacas",
    tagline: "The Wednesday-night summer party we keep going back to.",
    location: "Funchal",
    body: "Drive in, dinner then dancing, the kind of evening that runs late. Worth the trip even outside summer for the dinner alone: good seafood, good wine list, right on the water near the old fish factory.",
    body2: "In summer the Wednesdays are unmissable; the rest of the year it is just a really good restaurant.",
    practical: "Funchal, 45 min by car. Wednesday nights in summer. Dinner year-round.",
    lastVerified: "2026-06-15",
    distanceKm: 45,
    travelMinutes: 45,
    contact: { instagram: "https://www.instagram.com/docadocavacas/" },
    tags: ["party", "seafood", "summer"],
  },
];
