import type { GuideEntry } from "../types";

export const restaurants: GuideEntry[] = [
  {
    title: "Saboramar",
    slug: "saboramar",
    location: "Paul do Mar",
    body: "Grilled fish on a seafront terrace, straight from the morning boats. The hospitality here is on a different level from most of the island. Wine list is small but considered.",
    body2: "Show up early in summer for the terrace. Reservations do not quite work the way you would expect.",
    practical: "Paul do Mar, 12 km / 15 min from the house. Lunch and dinner. Reservations recommended in summer.",
    lastVerified: "2026-06-15",
    distanceKm: 12,
    travelMinutes: 15,
    tags: ["seafood", "terrace", "sunset"],
  },
  {
    title: "Restaurante Moreia",
    slug: "moreia",
    location: "Madalena do Mar",
    body: "Fresh fish and possibly the best arroz de marisco on the island. Ask about the wine cellar, especially the mainland whites. Family-run, unfussy, the kind of place that gets better the longer you sit.",
    practical: "Madalena do Mar, on the way back from Funchal. Long lunches.",
    lastVerified: "2026-06-15",
    distanceKm: 18,
    travelMinutes: 20,
    tags: ["seafood", "wine", "long lunch"],
  },
  {
    title: "Maktub",
    slug: "maktub",
    location: "Paul do Mar",
    body: "The end-of-day stop on the west side, a minute's walk from Saboramar. A touch louder and more social than its neighbour Bar da Pedra. Facing the water with the day closing down around you.",
    practical: "Paul do Mar, 12 km / 15 min from the house. Dinner and drinks. No reservations.",
    lastVerified: "2026-06-15",
    distanceKm: 12,
    travelMinutes: 15,
    contact: { instagram: "https://www.instagram.com/maktub_paulodomar/" },
    tags: ["dinner", "drinks", "sunset"],
  },
  {
    title: "Bar da Pedra",
    slug: "bar-da-pedra",
    location: "Paul do Mar",
    body: "The quieter pick next to Maktub. Same sunset, same ocean, different register. Nothing fancy, just exactly the right thing at the right hour.",
    practical: "Paul do Mar, 12 km / 15 min from the house. Evening.",
    lastVerified: "2026-06-15",
    distanceKm: 12,
    travelMinutes: 15,
    tags: ["drinks", "sunset", "quiet"],
  },
  {
    title: "Golden Calheta",
    slug: "golden-calheta",
    location: "Marina da Calheta",
    body: "Convenient and reliable, right on the marina. Good for after a boat trip or a swim. Solid food, decent service, a view of the boats. Lunch is the move.",
    practical: "Marina da Calheta, 6 km / 5 min from the house. Lunch and dinner.",
    lastVerified: "2026-06-15",
    distanceKm: 6,
    travelMinutes: 5,
    tags: ["marina", "lunch", "casual"],
  },
  {
    title: "Calheta Green",
    slug: "calheta-green",
    location: "Calheta",
    body: "The espetada spot. Madeiran skewered beef cooked over wood, eaten in the middle of greenery. They pull off the country-tavern thing without making it feel staged.",
    body2: "Good for groups, good for a slower lunch, good if guests want one proper Madeiran meal. A short drive inland from Calheta proper.",
    practical: "Calheta, 8 km / 10 min from the house. Lunch.",
    lastVerified: "2026-06-15",
    distanceKm: 8,
    travelMinutes: 10,
    tags: ["traditional", "espetada", "groups"],
  },
  {
    title: "Sunspot Cafe",
    slug: "sunspot-cafe",
    location: "Ponta do Sol",
    body: "Prego em bolo do caco or a burger, seafront, beer in hand, sunset doing its thing. No reservations needed for lunch. The place we end up at when we cannot decide on anything else.",
    practical: "Ponta do Sol, 15 km / 20 min from the house. All day.",
    lastVerified: "2026-06-15",
    distanceKm: 15,
    travelMinutes: 20,
    tags: ["casual", "burgers", "sunset"],
  },
  {
    title: "Razao by Octavio Freitas",
    slug: "razao",
    tagline: "The special-occasion meal on this side of the island.",
    location: "Socalco Nature Estate, Estreito da Calheta",
    body: "No menu, no choice. Farm-to-table tasting led by chef Octavio Freitas, formerly of Desarma in Funchal. The hotel is built into the vineyard terraces and the dining room reads as a quiet extension of that.",
    body2: "Reserve well ahead, clear the evening.",
    practical: "Estreito da Calheta, 10 min from the house. Dinner, tasting menu only. Reserve well ahead.",
    lastVerified: "2026-06-15",
    distanceKm: 5,
    travelMinutes: 10,
    tags: ["fine dining", "tasting menu", "special occasion"],
  },
  {
    title: "Vila do Peixe",
    slug: "vila-do-peixe",
    location: "Camara de Lobos",
    body: "Our default for special occasions, 30 minutes east. Sister restaurant to Vila da Carne, same owners, same standard. Works for a quiet dinner for two or a long table for eight.",
    body2: "Camara de Lobos itself is worth the drive in daylight; we tend to pair these with a walk along the harbour first.",
    practical: "Camara de Lobos, 30 min by car. Dinner. Reservations recommended.",
    lastVerified: "2026-06-15",
    distanceKm: 35,
    travelMinutes: 30,
    tags: ["seafood", "special occasion"],
  },
  {
    title: "Vila da Carne",
    slug: "vila-da-carne",
    location: "Camara de Lobos",
    body: "The meat counterpart to Vila do Peixe, same owners, same standard. Camara de Lobos itself is worth the drive in daylight.",
    practical: "Camara de Lobos, 30 min by car. Dinner. Reservations recommended.",
    lastVerified: "2026-06-15",
    distanceKm: 35,
    travelMinutes: 30,
    tags: ["meat", "special occasion"],
  },
];
